"""joining

Revision ID: 79eb284b65dd
Revises: 6bb7b1a659f6
Create Date: 2023-03-29 15:18:47.415570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79eb284b65dd'
down_revision = '6bb7b1a659f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
